### PR TITLE
feat(desktop & deck): Added XIV Launcher to list of available games

### PR DESCRIPTION
**Pull request by noelmiller**
Hi Team! 

Here is my PR! This adds the flatpak in the list of available games. This fixes https://github.com/ublue-os/bazzite/issues/380

Thanks, 

Noel Miller

### CODE REVIEW

**Comment by KyleGospo** [comment]
This is great, thank you so much!

**Review by KyleGospo — APPROVED** [review]

**Comment by KyleGospo** [comment]
We generate our change log from commit names, if you'd like this to appear in the change log you could append `feat: ` to your commit title.

**Comment by noelmiller** [comment]
I'm fairly new to git, is there an easy way to change a commit name?

**Comment by KyleGospo** [comment]
> I'm fairly new to git, is there an easy way to change a commit name?

Bit of a pain, editing is simple but then you need to force push, I'll merge and change on my end

**Comment by noelmiller** [comment]
Awesome! I did find the answer! https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/changing-a-commit-message

I'll make sure to be better about names in the future! This is the first public project I've ever committed to, so the process is still a bit new.

**Pull request merged**
