### PR TITLE
feat: Prepare mdBook workflow for documentation

### PR DESCRIPTION
**Pull request by Zeglius**
Add tooling (scripts, Github actions) in order to transcribe Discourse documentation to one using [mdBook](https://rust-lang.github.io/mdBook/) in efforts of improving accessibility when contributing to documentation.

Note: now with commit d42a29cb902035b76778ec183f4ef8904240c251, transcription is automated, staying in sync unidirectionally with discourse.

### CODE REVIEW

**Review by nicknamenamenick — APPROVED** [review]

**Comment by nicknamenamenick** [comment]
This is a better method to go about this, and I'd love for this to open the .desktop shortcut that we currently have.  Some of this documentation is outdated, has errors compared to how it is on Discourse, and I may remove some of the Handheld Wiki since that's ever-changing and probably best viewed before installing Bazzite.

**Review by Zeglius — COMMENTED** [review]
> This is a better method to go about this, and I'd love for this to open in the .desktop shortcut that we currently have.  Some of this documentation is outdated, has errors compared to how it is on Discourse, and I may remove some of the Handheld Wiki since that's ever-changing and probably best viewed before installing Bazzite. 

This gonna take longer that I expected, so I would rather suggest to not remove anything, rather add a warning that Discourse hosted docs might be deprecated. 

That is, only after we get a somewhat complete transcription to mdBooks

**Comment by nicknamenamenick** [comment]
I'd love to have a `ujust rtfm` eventually too!  Getting ahead of myself though, I won't remove anything from Discourse nor will I change the current offline doc files (but please note that several are outdated by now and they're most up to date on Discourse).  I will try not to touch the Discourse documentation for a while from this point forward, and if you need any feedback, help, or want to change some of the documentation yourself, ping me know on the Discord.

**Comment by Zeglius** [comment]
Renaming this PR from 'feat: Move documentation to mdBook' to 'feat: Prepare mdBook workflow for documentation'.
The reasoning is:
1. We don't want to deprecate Discourse hosted docs the moment this PR gets merged, so 'Move documentation' isn't fitting.
2. Providing tooling (CI setup, scripts, etc) and documentation dumped, all-in-one, is not feasible in a single PR, later better being provided over time.
3. Once merged, we can check if using mdBook for documentation is feasible at long term in a real-life scenario, when comes to accessibility for collaboration.

**Comment by noelmiller** [comment]
@Zeglius Could you provide a description of what this PR is attempting to achieve? I know there is discussion in here to provide more context, but it would be really helpful to have a summary at the top.

**Comment by KyleGospo** [comment]
@Zeglius Any luck on a local test? If this built I'm happy to merge

**Comment by Zeglius** [comment]
> @Zeglius Any luck on a local test? If this built I'm happy to merge

@KyleGospo all of my local builds worked so far so should be ready to go.

**Pull request merged**
