### PR TITLE
feat: Ship OpenGamepadUI

### PR DESCRIPTION
**Pull request by EyeCantCU**
This installs the binary version of OpenGamepadUI.

### CODE REVIEW

**Comment by EyeCantCU** [comment]
I want to adjust this to install via yafti and just. This would need a rewrite of the existing script for SteamOS installations though. I don't think it should be too bad

**Comment by EyeCantCU** [comment]
Additionally, due to the dependency on gamescope, it might be a good idea to omit this from desktop installations. Unsure on that

**Comment by EyeCantCU** [comment]
Because Steam is utilized in distrobox, the Steam plugin doesn't function entirely as it should. Thus, this should just be included in Deck images

**Comment by KyleGospo** [comment]
What's the issue preventing it from working exactly?

**Comment by KyleGospo** [comment]
SteamCMD is now included in the desk and desktop images, one native one in distrobox.

**Comment by EyeCantCU** [comment]
Just needs session select support

**Comment by EyeCantCU** [comment]
Session selection has been integrated

Todo:
- Add autostart capability to desktop images
- Just scriptlets for autologin
- Yafti integration
- OpenGamepadUI packaging

I will try and address all of those tomorrow

**Comment by EyeCantCU** [comment]
I believe only packaging remains

**Review by KyleGospo — APPROVED** [review]

**Review by KyleGospo — APPROVED** [review]

**Review by KyleGospo — APPROVED** [review]

**Review by KyleGospo — APPROVED** [review]

**Review by KyleGospo — APPROVED** [review]

**Review by KyleGospo — APPROVED** [review]

**Pull request closed without merging**
