### PR TITLE
Added a help section to the justfile

### PR DESCRIPTION
**Pull request by dnkmmr69420**
Modify it to your needs

### Guidelines
In this project we follow [Semantic PRs][1] and [Conventional Commits][2] to describe features and fixes we made. It would be nice if you did too. Not sure what this all means? Here are some [examples][3]. Did you already use this? Awesome, thanks again!

[1]: https://github.com/Ezard/semantic-prs
[2]: https://www.conventionalcommits.org/en/v1.0.0/#summary
[3]: https://www.conventionalcommits.org/en/v1.0.0/#examples

### CODE REVIEW

**Comment by dnkmmr69420** [comment]
but how will people to know what commands are available that does not involve looking at the source code?

**Comment by bigpod98** [comment]
Isnt there just list or something like that that lists just commands

**Comment by bigpod98** [comment]
Its just --list but ok

**Comment by castrojo** [comment]
`just` by itself shows the individual help snippets for each one.

image

**Comment by dnkmmr69420** [comment]
I never knew that existed. I think there should be something on the very top because if you just type `just` it automatically removes arch-bazzite and reinstalls the container. The first thing should be like this

```
all:
      echo 'type 'justfile --list' for help
```

**Comment by castrojo** [comment]
Mine works like it's supposed to, there's probably something specific in the bazzite custom one that is overriding it that we should probably fix.

**Comment by KyleGospo** [comment]
Thanks, I used your work here to implement the same concept in this way:
https://github.com/ublue-os/bazzite/commit/74e9506a77414202fb534508e2cda3d252b8c88d

**Pull request closed without merging**
