### PR TITLE
fix: source LACT from copr instead of downloading from releases page

### PR DESCRIPTION
**Pull request by porkloin**
LACT now has a [copr](https://copr.fedorainfracloud.org/coprs/ilyaz/LACT/) and this updates the `yum.repos.d` to contain the repo file for that copr, and updated the `ujust` command to fetch via rpm-ostree instead of bash script to download from the releases page.

### CODE REVIEW

**Comment by KyleGospo** [comment]
This is great, thank you! 

One request, can we pull the copr repo in the container file like we do for the current ones?

**Comment by porkloin** [comment]
> This is great, thank you!
> 
> One request, can we pull the copr repo in the container file like we do for the current ones?

Done!

**Review by KyleGospo — APPROVED** [review]

**Comment by porkloin** [comment]
@KyleGospo sorry I saw you enabled auto-merge but I realized there was some stuff in the ujust that I didn't mean to delete, especially enabling the systemd unit

**Comment by porkloin** [comment]
Nevermind, I realized I also needed to remove the LACT stuff from topgrade! For real this time, I think I'm done :stuck_out_tongue:

**Review by KyleGospo — APPROVED** [review]

**Review by HikariKnight — APPROVED** [review]

**Pull request merged**
