### PR TITLE
chore: Switch from dconf to gschema-overrides

### PR DESCRIPTION
**Pull request by fiftydinar**
See Bluefin's PR for more details:
https://github.com/ublue-os/bluefin/pull/1716

It's in draft just for testing

I see that you load dconf in some scripts, I'll have to see how to solve this with gschema-overrides

### CODE REVIEW

**Comment by fiftydinar** [comment]
I finished dconf loading support from gschemas.

So only testing is needed now.

**Review by KyleGospo — APPROVED** [review]

**Review by KyleGospo — APPROVED** [review]

**Comment by KyleGospo** [comment]
@fiftydinar Thanks, finally got this to run. Had to make some major changes for the negativo patch upstream. If you could fix up those two conflicts I'll merge this right away.

**Comment by fiftydinar** [comment]
@KyleGospo Did you test the image? I'm asking because I did not test this fully

**Comment by fiftydinar** [comment]
@KyleGospo Conflicts should be resolved

**Comment by KyleGospo** [comment]
@fiftydinar Close, syntax error in just

**Comment by fiftydinar** [comment]
@KyleGospo Can't pinpoint where is the syntax error in just. Looks good to me so far

**Comment by fiftydinar** [comment]
Oh, forgot that there is ujust syntax checker, will fix the non-harming whitespace

**Comment by fiftydinar** [comment]
@KyleGospo justfile syntax should be fixed now (ran tests with `just --fmt --check --unstable --justfile "${justfile}"`)

**Comment by fiftydinar** [comment]
Containerfile syntax error.

Idk why is ; added tbh, just saw how it's done in other parts

Have to see why this happens

**Pull request merged**
