### PR TITLE
fix(steam): Do not preload extest in KDE plasma

### PR DESCRIPTION
**Pull request by Zeglius**
This would fix issue #1675 in KDE images

### CODE REVIEW

**Review by KyleGospo — DISMISSED** [review]

**Comment by HikariKnight** [comment]
Wont this break steam input on KDE? like the Desktop Layout and such.

**Comment by Zeglius** [comment]
> Wont this break steam input on KDE? like the Desktop Layout and such.

Didn't think of that. Thanks for pointing  that out. 
Probably this should do better in the testing branch.

**Comment by HikariKnight** [comment]
im more comfortable with this in testing to test it properly first, will do some testing after work tomorrow to check steam input as i rely on it a lot on desktop

**Review by HikariKnight — APPROVED** [review]

**Comment by HikariKnight** [comment]
@Zeglius i have tested this today, seems to not impact steam input just gives a dialog asking for remote input access and once granted seem to not ask again (will check again after reboot) but so far seems good.

**Comment by Zeglius** [comment]
> ok so after every reboot (or relogin) the user will have to re-accept the remote control prompt when trying to use steam input with steam chords (like opening the keyboard), this i can imagine is fine on the desktop image not on the `-deck` image
> image
> 
> Also when i tested it did not fix the big picture mode lag on my end :thinking: 
> 

How did you test this? This PR seems didn't get merged in `:testing`.

**Comment by Zeglius** [comment]
Ok so I have been testing a little bit and seems extest is not the cause of the lag.

I could reproduce the lag by launching bazzite-steam in the terminal, **but not when launching from the app menu**

I checked the difference between both, from terminal and from app menu, and it seems it was switcheroo all along, which doesnt inject the required env vars when in terminal.

As soon I launched bazzite-steam with `switcheroo launch bazzite-steam`, the lag was gone

**Comment by HikariKnight** [comment]
> > ok so after every reboot (or relogin) the user will have to re-accept the remote control prompt when trying to use steam input with steam chords (like opening the keyboard), this i can imagine is fine on the desktop image not on the `-deck` image
> > image
> > Also when i tested it did not fix the big picture mode lag on my end 🤔
> 
> How did you test this? This PR seems didn't get merged in `:testing`.

just downloaded the script and tested with that :D

**Pull request closed without merging**
