### PR TITLE
fix(deck): Use super + 1/2 for Overlay/QAM

### PR DESCRIPTION
**Pull request by AkazaRenn**
For https://github.com/ublue-os/bazzite/issues/1720. The reason I'm not using shift + tab is that it just doesn't work... I think Steam in deck mode ignores that key combination. This should still be a safe combination since that's a Windows reserved hotkey and no game would consider using it.

I've tested this change to be working as expected by building the binary and replacing it at /usr/bin/gamescope

### CODE REVIEW

**Comment by antheas** [comment]
We cannot merge this yet as certain functionality relies on it. However, this patch looks really interesting.

**Comment by AkazaRenn** [comment]
> We cannot merge this yet as certain functionality relies on it. However, this patch looks really interesting.

Is there anything I can help? It would be nice to get this merged so we no longer block ctrl-hotkeys.

**Comment by antheas** [comment]
Modify this patch to include two env vars: one for disabling ctrl + 1/2, and one for enabling win + 1/2.

Then this patch can merge without breaking other stuff, and we can slowly work on transitioning to win + 1/2.

Specifically, hhd uses ctrl+1/2 on tablets so it would need to coordinate with the win env var. Also, a lot of users have started depending on ctrl+1/2.

**Comment by antheas** [comment]
Probably both ctrl/win+1/2 will co-exist for a few months. Specifically, ctrl + 1/2 causes issues in certain games. You are right.

**Comment by AkazaRenn** [comment]
> Probably both ctrl/win+1/2 will co-exist for a few months. Specifically, ctrl + 1/2 causes issues in certain games. You are right. This is even if the user does not want to use it in-game.

What you mean is that we add an environment variable check, if that's true, we still passthrough ctrl + 1/2?

**Comment by antheas** [comment]
The ctrl + 1/2 needs to be opt out (i.e., var disables it). win + 1/2 needs to be opt in (i.e. var enables it).

Otherwise this patch will take a lot longer to merge.

**Comment by AkazaRenn** [comment]
> The ctrl + 1/2 needs to be opt out (i.e., var disables it). win + 1/2 needs to be opt in (i.e. var enables it).
> 
> Otherwise this patch will take a lot longer to merge.

I can help make this change, but I don't know about personal configurations on Bazzite. Where do we do this opt-in/out?

**Comment by antheas** [comment]
For these things, you can add a variable to `/etc/environment.d` and it will apply to gamescope. This way you could use win + 1/2 in your personal machine.

**Comment by antheas** [comment]
Use the variables `GS_CTRL12_DISABLE` and `GS_WIN12_ENABLE` and reference other gamescope patches to see how to fit them in.

**Comment by AkazaRenn** [comment]
> Use the variables `GS_CTRL12_DISABLE` and `GS_WIN12_ENABLE` and reference other gamescope patches to see how to fit them in. 

Thanks, I'll start working on it.

**Comment by AkazaRenn** [comment]
f1fa969f16181b712c375de98d82cf875ed26464
`GS_ENABLE_CTRL_12` in `/etc/environment` commented out, not existing == true for update compatibility. I didn't add another one for `super` because that's not causing any troubles and feel like it's unnecessary.

**Review by KyleGospo — APPROVED** [review]

**Review by HikariKnight — APPROVED** [review]

**Comment by AkazaRenn** [comment]
Hi @antheas, this change has been added to the latest `testing` branch of Bazzite and I've tested it to be fully functional. You may consider adjusting the HHD codes to rely on `super + 1/2` instead so we can drop the option in the future. Thanks a lot for your help!

**Pull request merged**
