### PR TITLE
feat: Implement GNOME images

### PR DESCRIPTION
**Pull request by EyeCantCU**
These changes provide initial support for GNOME Bazzite images

### CODE REVIEW

**Comment by EyeCantCU** [comment]
Caveats: The Deck Gnome images use Wayland; not X11 which could be problematic for input. The just files haven't been updated yet and neither has the yafti configuration so I'd imagine quite a bit of that is no-op at the moment

**Comment by EyeCantCU** [comment]
All aforementioned issues should be worked out

**Comment by KyleGospo** [comment]
> All aforementioned issues should be worked out

What are your thoughts on getting these to start building? If it's not ready for a 1.0 we can always just not advertise these

**Review by KyleGospo — APPROVED** [review]

**Review by EyeCantCU — COMMENTED** [review]
Everything here looks fantastic and ready to go!

**Comment by KyleGospo** [comment]
LGTM

**Pull request merged**
