### PR TITLE
added an option to enable flatpak theming with accent colors in the justfile

### PR DESCRIPTION
**Pull request by dnkmmr69420**

### CODE REVIEW

**Comment by KyleGospo** [comment]
Is this needed for anything in Bazzite? Currently Gradience adds these rules when a theme is applied via Bazzite Portal.

**Comment by EyeCantCU** [comment]
> Is this needed for anything in Bazzite? Currently Gradience adds these rules when a theme is applied via Bazzite Portal.

Could possibly be useful if someone doesn't apply one of the default themes, or sticks with Adwaita (and enables the dark mode for instance). I am curious why this is done on the user level and not system level though

**Comment by KyleGospo** [comment]
That's fair, if that's the case let's also do
`~/.icons:ro`
`~/.themes:ro`

**Comment by KyleGospo** [comment]
Addressed in latest commit, thanks!

**Pull request closed without merging**
