### PR TITLE
feat: Replace power profiles daemon with TuneD

### LINKED ISSUE #584: Suggestion: Replace Power-Profiles-Daemon with TuneD and TuneD-GTK
I keep hearing from the community that TuneD works so much better that P-P-D and for my Dell XPS 15 9510 it seems to work a little bit better so please consider this for Bazzite and maybe even all the other Ublue images. Thanks in advance!

### PR DESCRIPTION
**Pull request by EyeCantCU**
Provides more control over power tuning. May be the default in Fedora 40 with one of the only blockers being the lack of GNOME Control Center integration (tuned-gtk provides a GUI for this in the meantime)

Proposal: https://discussion.fedoraproject.org/t/f40-change-proposal-tuned-replaces-power-profiles-daemon-self-contained/94995

Resolves #584

### CODE REVIEW

**Comment by EyeCantCU** [comment]
Needs gamescope-session integration (working on it) and testing

**Comment by EyeCantCU** [comment]
gamescope-session PR: https://github.com/KyleGospo/gamescope-session/pull/56

**Comment by KyleGospo** [comment]
https://github.com/redhat-performance/tuned/pull/579/

**Comment by KyleGospo** [comment]
Also includes https://github.com/redhat-performance/tuned/pull/579

**Comment by KyleGospo** [comment]
Merging into main-next, closing as a result

**Comment by KyleGospo** [comment]
One issue left to solve where switching your power profile causes shutdown to hang for a long time while it waits for services to stop

**Pull request merged**
